server:
  port: 8888

spring:
  application:
    name: fake-group
  liquibase:
    enabled: true
    change-log: classpath:liquibase/databaseChangeLog.xml
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    url: ${DB_URL:jdbc:mysql://localhost:3306}/quizdb?autoReconnect=true&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource